name: Publish .hex Files from Latest Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get latest release info
        id: release_info
        run: |
          release_json=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/latest)
          asset_names=$(echo $release_json | jq -r '.assets[].name')
          asset_urls=$(echo $release_json | jq -r '.assets[].url')
          echo "::set-output name=asset_names::${asset_names}"
          echo "::set-output name=asset_urls::${asset_urls}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and publish .hex files
        run: |
          readarray -t names <<< "${{ steps.release_info.outputs.asset_names }}"
          readarray -t urls <<< "${{ steps.release_info.outputs.asset_urls }}"
          for ((i=0;i<${#names[@]};i++)); do
            asset_name="${names[$i]}"
            asset_url="${urls[$i]}"
            if [[ "$asset_name" == *.hex ]]; then
              curl -s -L -o "$asset_name" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$asset_url"
              echo "Uploading $asset_name as an artifact"
              echo "::set-env name=CURRENT_HEX_FILE::$asset_name"
              echo "$asset_name" > current_hex_file.txt
              gh workflow run upload-hex-file.yml --ref ${{ github.ref }} --field hex_file=current_hex_file.txt
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

