name: Download and Upload .hex File from Latest Release

on:
  workflow_dispatch:

jobs:
  process_hex_file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download .hex file from latest release
        uses: robinraju/release-downloader@v1.9
        with:
          latest: true
          filename: "*.hex"
          target: "./"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Find .hex file
        id: find_file
        run: |
          hex_file=$(ls *.hex)
          echo "::set-output name=hex_file_name::${hex_file}"

      - name: Upload .hex file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.find_file.outputs.hex_file_name }}
          path: ${{ steps.find_file.outputs.hex_file_name }}
