name: Publish Single .hex File from Latest Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get latest release info
        id: release_info
        run: |
          release_json=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/latest)
          asset_name=$(echo $release_json | jq -r '.assets[] | select(.name | endswith(".hex")).name')
          asset_url=$(echo $release_json | jq -r '.assets[] | select(.name | endswith(".hex")).url')
          echo "::set-output name=asset_name::${asset_name}"
          echo "::set-output name=asset_url::${asset_url}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download .hex file
        run: |
          asset_name="${{ steps.release_info.outputs.asset_name }}"
          asset_url="${{ steps.release_info.outputs.asset_url }}"
          curl -s -L -o "$asset_name" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/octet-stream" "$asset_url"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .hex file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.release_info.outputs.asset_name }}
          path: ${{ steps.release_info.outputs.asset_name }}
